-- Discount Code Usage Audit Table
-- Created: 2025-10-28

CREATE TABLE IF NOT EXISTS khm_discount_codes_uses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    discount_code_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    order_id BIGINT UNSIGNED DEFAULT NULL,
    used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45) DEFAULT NULL,
    session_id VARCHAR(64) DEFAULT NULL,
    FOREIGN KEY (discount_code_id) REFERENCES khm_discount_codes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
