CREATE TABLE `khm_membership_levels` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `confirmation` longtext NOT NULL,
  `initial_payment` decimal(10,2) NOT NULL DEFAULT 0.00,
  `billing_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cycle_number` int(11) NOT NULL DEFAULT 0,
  `cycle_period` enum('Day','Week','Month','Year') NOT NULL DEFAULT 'Month',
  `billing_limit` int(11) NOT NULL DEFAULT 0,
  `trial_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `trial_limit` int(11) NOT NULL DEFAULT 0,
  `allow_signups` tinyint(1) NOT NULL DEFAULT 1,
  `expiration_number` int(10) unsigned NOT NULL DEFAULT 0,
  `expiration_period` enum('Day','Week','Month','Year') NOT NULL DEFAULT 'Month',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_allow_signups` (`allow_signups`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `khm_membership_levelmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `level_id` bigint(20) unsigned NOT NULL,
  `meta_key` varchar(255) NOT NULL,
  `meta_value` longtext DEFAULT NULL,
  PRIMARY KEY (`meta_id`),
  KEY `idx_level_id` (`level_id`),
  KEY `idx_meta_key` (`meta_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `khm_memberships_users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `membership_id` bigint(20) unsigned NOT NULL,
  `code_id` bigint(20) unsigned DEFAULT NULL,
  `initial_payment` decimal(10,2) NOT NULL DEFAULT 0.00,
  `billing_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cycle_number` int(11) NOT NULL DEFAULT 0,
  `cycle_period` enum('Day','Week','Month','Year') NOT NULL DEFAULT 'Month',
  `billing_limit` int(11) NOT NULL DEFAULT 0,
  `trial_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `trial_limit` int(11) NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `startdate` datetime NOT NULL,
  `enddate` datetime DEFAULT NULL,
  `modified` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `membership_id` (`membership_id`),
  KEY `status` (`status`),
  KEY `modified` (`modified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `khm_membership_orders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `session_id` varchar(128) DEFAULT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `membership_id` bigint(20) unsigned NOT NULL,
  `paypal_token` varchar(128) DEFAULT NULL,
  `billing_name` varchar(191) DEFAULT NULL,
  `billing_street` varchar(191) DEFAULT NULL,
  `billing_city` varchar(191) DEFAULT NULL,
  `billing_state` varchar(64) DEFAULT NULL,
  `billing_zip` varchar(32) DEFAULT NULL,
  `billing_country` varchar(128) DEFAULT NULL,
  `billing_phone` varchar(32) DEFAULT NULL,
  `subtotal` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tax` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total` decimal(10,2) NOT NULL DEFAULT 0.00,
  `payment_type` varchar(64) DEFAULT NULL,
  `cardtype` varchar(64) DEFAULT NULL,
  `accountnumber` varchar(64) DEFAULT NULL,
  `expirationmonth` char(2) DEFAULT NULL,
  `expirationyear` varchar(4) DEFAULT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'pending',
  `gateway` varchar(64) DEFAULT NULL,
  `gateway_environment` varchar(64) DEFAULT NULL,
  `payment_transaction_id` varchar(128) DEFAULT NULL,
  `subscription_transaction_id` varchar(128) DEFAULT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `affiliate_id` varchar(64) DEFAULT NULL,
  `affiliate_subid` varchar(64) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` text DEFAULT NULL,
  `failure_at` datetime DEFAULT NULL,
  `refund_amount` decimal(10,2) DEFAULT NULL,
  `refund_reason` text DEFAULT NULL,
  `refunded_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `code` (`code`),
  KEY `session_id` (`session_id`),
  KEY `user_id` (`user_id`),
  KEY `membership_id` (`membership_id`),
  KEY `status` (`status`),
  KEY `timestamp` (`timestamp`),
  KEY `gateway` (`gateway`),
  KEY `gateway_environment` (`gateway_environment`),
  KEY `payment_transaction_id` (`payment_transaction_id`(64)),
  KEY `subscription_transaction_id` (`subscription_transaction_id`(64)),
  KEY `idx_failure_at` (`failure_at`),
  KEY `idx_refunded_at` (`refunded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


